# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Creditos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
