# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Academico', '0002_estudiante_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='Actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
