# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-03 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Academico', '0004_remove_matricula_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='CreditosDis',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
